version: "3.9"

services:
  agent-swarm:
    build: .
    container_name: agent-swarm-app
    ports:
      - "8001:8001"  # FastAPI
      - "8000:8000"  # Streamlit
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

